Nova pasta/ProjetoE21/Controllers/EmpregosController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using ProjetoE21.Dados;
using ProjetoE21.Dao;
using ProjetoE21.Models;
using ProjetoE21.Ordenacao;

namespace ProjetoE21.Controllers
{
    public class EmpregosController : Controller
    {
        OrdenarEmpregos ordena = new();
        DaoEmprego DaoS = new();
        DaoCurriculo DaoCur = new();

        public IActionResult Index(string sorter, string currentFilter, string searchString, int? page)
        {
            Listas.empregos = DaoS.consultar();

            ViewBag.CurrentSort = sorter;
            ViewBag.descSort = "nome_desc";
            ViewBag.Sort = "nome";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            ordena.Pesquisa(searchString);

            ViewBag.CurrentFilter = searchString;

            ordena.Ordena(sorter);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(Listas.empregos.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Adicionar(Emprego emprego)
        {
            if (!ModelState.IsValid)
            {
                return View(emprego);
            }

            DaoS.adicionar(emprego);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Emprego emprego = Listas.empregos.FirstOrDefault(sc => sc.Id == id);

            return View(emprego);
        }

        [HttpPost]
        public IActionResult Delete(Emprego emprego)
        {
            DaoS.deletar(emprego);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Emprego emprego = Listas.empregos.FirstOrDefault(sc => sc.Id == id);

            return View(emprego);
        }

        [HttpPost]
        public IActionResult Edit(Emprego emprego)
        {
            if (!ModelState.IsValid)
            {
                return View(emprego);
            }

            DaoS.editar(emprego);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Emprego emprego = Listas.empregos.FirstOrDefault(s => s.Id == id);

            return View(emprego);
        }

        public IActionResult Candidatos(int id)
        {
            List<Curriculo> candidatos = DaoCur.consultarCandidatos(id);

            return View(candidatos);
        }
    }
}

Nova pasta/ProjetoE21/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoE21.Models;
using ProjetoE21.Dados;
using ProjetoE21.Dao;

namespace ProjetoE21.Controllers
{
    public class PerfilController : Controller
    {
        DaoCadastro DaoC = new();
        DaoCurriculo DaoCur = new();
        DaoEmpresa DaoEmp = new();
        DaoFavoritos DaoF = new();
        DaoEmprego DaoE = new();

        public IActionResult Index()
        {
            if (Usuario.LogadoE == null)
            {
                return RedirectToAction("Jovem");
            }
            else
            {
                return RedirectToAction("Empresa");
            }
        }

        public IActionResult Desfavoritar(int id)
        {
            List<Emprego> empregos = DaoE.consultar();

            Emprego emprego = empregos.FirstOrDefault(em => em.Id == id);

            DaoF.deletar(emprego);

            return RedirectToAction("Jovem");
        }

        public IActionResult Jovem()
        {
            Listas.favoritos = DaoF.consultar();

            return View();
        }

        public IActionResult Empresa()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Editar()
        {
            Jovem jovem = Listas.cadastrosJ.FirstOrDefault(sc => sc.Id == Usuario.LogadoJ.Id);

            return View(jovem);
        }

        [HttpPost]
        public IActionResult Editar(Jovem jovem)
        {
            jovem.Id = Usuario.LogadoJ.Id;

            if (!ModelState.IsValid)
            {
                return View(jovem);
            }

            DaoC.editar(jovem);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditarEmpresa()
        {
            Empresa empresa = Listas.cadastrosE.FirstOrDefault(sc => sc.Id == Usuario.LogadoE.Id);

            return View(empresa);
        }

        [HttpPost]
        public IActionResult EditarEmpresa(Empresa empresa)
        {
            empresa.Id = Usuario.LogadoE.Id;

            if (!ModelState.IsValid)
            {
                return View(empresa);
            }

            DaoEmp.editar(empresa);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Curriculo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Curriculo(Curriculo curriculo)
        {
            curriculo.Nome = Usuario.LogadoJ.Nome;

            curriculo.Local = new();

            curriculo.Local = Usuario.LogadoJ.Local;
            curriculo.Telefone = Usuario.LogadoJ.Telefone;
            curriculo.Email = Usuario.LogadoJ.Email;

            DaoCur.adicionar(curriculo);

            List<Curriculo> curriculos = DaoCur.consultar();

            Usuario.LogadoJ.Curriculo = curriculos.FirstOrDefault(cr => cr.JovemId == Usuario.LogadoJ.Id);

            return RedirectToAction("Index");
        }
    }
}

Nova pasta/ProjetoE21/Controllers/PesquisarController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoE21.Dao;
using ProjetoE21.Ordenacao;
using ProjetoE21.Models;
using ProjetoE21.Dados;

namespace ProjetoE21.Controllers
{
    public class PesquisarController : Controller
    {
        OrdenaJovens ordena = new();
        DaoCadastro DaoC = new();
        DaoCurriculo DaoCur = new();

        public IActionResult Index(string searchString)
        {
            Listas.cadastrosJ = DaoC.consultar();

            ViewBag.CurrentFilter = searchString;

            ordena.Pesquisa(searchString);

            return View(Listas.cadastrosJ);
        }

        public IActionResult Ver(int id)
        {
            List<Jovem> jovens = DaoC.consultar();

            List<Curriculo> curriculos = DaoCur.consultar();

            Jovem jovem = jovens.FirstOrDefault(jv => jv.Id == id);

            jovem.Curriculo = curriculos.FirstOrDefault(cr => cr.JovemId == id);

            return View(jovem);
        }
    }
}

Nova pasta/ProjetoE21/Controllers/ServiçosController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoE21.Models;
using ProjetoE21.Dados;
using ProjetoE21.Dao;
using X.PagedList;
using ProjetoE21.Ordenacao;

namespace ProjetoE21.Controllers
{
    public class ServiçosController : Controller
    {
        OrdenarServicos ordenar = new();
        DaoServico DaoS = new();
        public IActionResult Index(string sorter, string currentFilter, string searchString, int? page)
        {
            Listas.servicos = DaoS.consultar();

            ViewBag.CurrentSort = sorter;
            ViewBag.descSort = "nome_desc";
            ViewBag.Sort = "nome";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            ordenar.Pesquisa(searchString);

            ViewBag.CurrentFilter = searchString;

            ordenar.Ordena(sorter);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(Listas.servicos.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Adicionar(Servico servico)
        {
            servico.EmpresaS = new();

            servico.EmpresaS.Id = 1;
            servico.EmpresaS.Nome = "Empresa inventada";

            servico.Dia = $"{servico.Horario.Day}/{servico.Horario.Month}/{servico.Horario.Year}";
            servico.Hora = $"{servico.Horario.TimeOfDay}";

            if (!ModelState.IsValid)
            {
                return View(servico);
            }

            DaoS.adicionar(servico);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Servico servico = Listas.servicos.FirstOrDefault(sc => sc.Id == id);

            return View(servico);
        }

        [HttpPost]
        public IActionResult Delete(Servico servico)
        {
            DaoS.deletar(servico);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Servico servico = Listas.servicos.FirstOrDefault(sc => sc.Id == id);

            return View(servico);
        }

        [HttpPost]
        public IActionResult Edit(Servico servico)
        {
            servico.EmpresaS = new();

            servico.EmpresaS.Id = 1;
            servico.EmpresaS.Nome = "Empresa inventada";

            servico.Dia = $"{servico.Horario.Day}/{servico.Horario.Month}/{servico.Horario.Year}";
            servico.Hora = $"{servico.Horario.TimeOfDay}";

            if (!ModelState.IsValid)
            {
                return View(servico);
            }

            DaoS.editar(servico);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Servico servico = Listas.servicos.FirstOrDefault(s => s.Id == id);

            return View(servico);
        }
    }
}

Nova pasta/ProjetoE21/Views/Shared/_Layout.cshtml
@using ProjetoE21.Dados

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoE21</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoE21.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Aside.css" />
    <link rel="stylesheet" href="~/css/Login.css" />

    <style>
        .asd {
            display: none;
        }

        .asdEnter {
            animation: AsideEnter 0.25s ease-in;
        }

        .asd-item {
        }

            .asd-item:hover {
                background-color: rgba(0, 0, 0, 0.25);
                cursor: pointer;
            }

        .dark-mode2 {
            filter: invert(80%);
        }
    </style>
</head>

<body style="background-color:rgb(246, 245, 252);">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container-fluid" style="height: 3rem">
                <a style="width: 20%; margin-right: 8px; display: flex; align-items: center" asp-controller="Perfil" asp-action="Index">
                    <img src="~/css/Imagens/Perfil.png" width="20%" class="m-1"></img>
                    <p style="margin-top: 1rem">
                        @if (Usuario.LogadoE == null)
                        {
                            @Usuario.LogadoJ.Nome
                            ;

                        }
                        else
                        {
                            @Usuario.LogadoE.Nome
                            ;
                        }
                    </p>
                </a>
                <a class="navbar-brand d-flex" asp-area="" asp-controller="Home" asp-action="Index" style="font-size: 32px; font-family: Arial; margin-top: 4px">
                    <p id="oppor" style="color: #7CDFE5">Oppor</p>
                    <p id="teen" style="color: #A378FF">teen</p>
                    <p id="ity" style="color: #E21EAD">ity</p>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">




                        @if (Usuario.LogadoE == null)
                        {


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Serviços" asp-action="Index">Serviços</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empregos" asp-action="Index">Empregos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pesquisar" asp-action="Index">Jovens</a>
                            </li>
                        }

                    </ul>
                    <div class="d-flex me-5 mt-0">
                        <button onclick="aside()" class="btn btn-secondary w-100" type="button" id="config">
                            Configurações
                        </button>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container d-flex justify-content-center" style="min-height: 100vh;min-width:98vw; padding-top: 56px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjetoE21 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        if (localStorage.getItem("dm") == "yes") {
            document.getElementsByTagName("html")[0].classList.add("dark-mode2");
            document.getElementById("oppor").style.color = "#cda6a3";
            document.getElementById("teen").style.color = "#becf99";
            document.getElementById("ity").style.color = "#a5f3ba";
        }

        if (!localStorage.getItem("dm")) {
            localStorage.setItem("dm", "no");
            document.getElementById("oppor").style.color = "#7CDFE5";
            document.getElementById("teen").style.color = "#A378FF";
            document.getElementById("ity").style.color = "#E21EAD";
        }

        function darkMode() {
            document.getElementsByTagName("html")[0].classList.add("dark-mode2");
            document.getElementById("oppor").style.color = "#cda6a3";
            document.getElementById("teen").style.color = "#becf99";
            document.getElementById("ity").style.color = "#a5f3ba";
            document.getElementById("dm").innerHTML = "Light mode";
            document.getElementById("dm").onclick = "lightMode()";
            localStorage.setItem("dm", "yes");

            asideRemove();
        }

        function lightMode() {
            document.getElementsByTagName("html")[0].classList.remove("dark-mode2");
            document.getElementById("oppor").style.color = "#7CDFE5";
            document.getElementById("teen").style.color = "#A378FF";
            document.getElementById("ity").style.color = "#E21EAD";
            document.getElementById("dm").innerHTML = "Dark mode";
            document.getElementById("dm").onclick = "darkMode()";
            localStorage.setItem("dm", "no");

            asideRemove();
        }

        function aside() {
            if (localStorage.getItem("dm") == "no") {
                document.getElementById("config").insertAdjacentHTML("afterend", `<aside class="asdEnter position-absolute end-0 bg-light rounded p-2 mt-0" style="height: 98vh; width:25%; box-shadow: -10px 10px 15px -4px rgba(0,0,0,0.75);" id="aside">
                                                                                                                                     <div class="rounded w-100 asd-item p-2" onclick="asideRemove()">X</div>
                                                                                                                                     <div class="rounded w-100 asd-item p-2" id="dm" onclick="darkMode()">Dark mode</div>
                                                                                                                                     <div class="rounded w-100 asd-item p-2">Minha conta</div>
                                                                                                                                     <div class="rounded w-100 asd-item p-2 position-absolute" style="bottom: 16px">Sair da conta</div>
                                                                                                                              </aside>`);
            } else {
                document.getElementById("config").insertAdjacentHTML("afterend", `<aside class="asdEnter position-absolute end-0 bg-light rounded p-2 mt-0" style="height: 98vh; width:25%; box-shadow: -10px 10px 15px -4px rgba(0,0,0,0.75);" id="aside">
                                                                                                                                             <div class="rounded w-100 asd-item p-2" onclick="asideRemove()">X</div>
                                                                                                                                             <div class="rounded w-100 asd-item p-2" id="dm" onclick="lightMode()">Light mode</div>
                                                                                                                                             <div class="rounded w-100 asd-item p-2">Minha conta</div>
                                                                                                                                             <div class="rounded w-100 asd-item p-2 position-absolute" style="bottom: 16px">Sair da conta</div>
                                                                                                                                      </aside>`);
            }
        }

        function asideRemove() {
            document.getElementById("aside").remove("asd");
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>