CadastroProjeto/Models/Empresa.cs
namespace CadastroProjeto.Models
{
    public class Empresa
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string NomeLocal { get; set; }
        public string Rua { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string CEP { get; set; }
        public string UF { get; set; }
        public string Pais { get; set; }
    }
}

CadastroProjeto/Models/ErrorViewModel.cs
namespace CadastroProjeto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroProjeto/Models/Jovem.cs
namespace CadastroProjeto.Models
{
    public class Jovem
    {
        public int Id {  get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public int DataNascimento { get; set; }
        public string NomeLocal { get; set; }
        public string Rua { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string CEP { get; set; }
        public string UF { get; set; }
        public string Pais { get; set; }
    }
}

CadastroProjeto/Controllers/EmpresaController.cs
using Microsoft.AspNetCore.Mvc;

namespace CadastroProjeto.Controllers
{
    public class EmpresaController : Controller
    {       
        public IActionResult Index()
        {
            return View(Dados.Db.empresas);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Models.Empresa empresa)
        {
            empresa.Id = Dados.Db.empresas.Count + 1;
            Dados.Db.empresas.Add(empresa);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            Models.Empresa empresa = Dados.Db.empresas.FirstOrDefault(em => em.Id == id);
            return View(empresa);
        }

        [HttpPost]
        public IActionResult Edit(Models.Empresa empresa)
        {
            Models.Empresa emp = Dados.Db.empresas.FirstOrDefault(em => em.Id == empresa.Id);
            emp.Nome = empresa.Nome;
            emp.Email = empresa.Email;
            emp.Telefone = empresa.Telefone;
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int? id)
        {
            Models.Empresa empresa = Dados.Db.empresas.FirstOrDefault(em => em.Id == id);
            return View(empresa);
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            Models.Empresa empresa = Dados.Db.empresas.FirstOrDefault(em => em.Id == id);
            return View(empresa);
        }

        [HttpPost]
        public IActionResult Delete(Models.Empresa empresa)
        {
            Models.Empresa EmpresaParaRemover = Dados.Db.empresas.FirstOrDefault(em => em.Id == empresa.Id);
            Dados.Db.empresas.Remove(EmpresaParaRemover);
            return RedirectToAction("Index");
        }

    }
}

CadastroProjeto/Controllers/HomeController.cs
using CadastroProjeto.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CadastroProjeto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroProjeto/Controllers/JovemController.cs
using Microsoft.AspNetCore.Mvc;

namespace CadastroProjeto.Controllers
{
    public class JovemController : Controller
    {
        public IActionResult Index()
        {
            return View(Dados.Db.jovens);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Models.Jovem jovem)
        {
            jovem.Id = Dados.Db.jovens.Count + 1;
            Dados.Db.jovens.Add(jovem);
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            Models.Jovem jovem = Dados.Db.jovens.FirstOrDefault(jv => jv.Id == id);
            return View(jovem);
        }
                [HttpPost]
        public IActionResult Edit(Models.Jovem jovem)
        {
            Models.Jovem jov = Dados.Db.jovens.FirstOrDefault(jv => jv.Id == jovem.Id);
            jov.Nome = jovem.Nome;
            jov.Email = jovem.Email;
            jov.Telefone = jovem.Telefone;
            jov.DataNascimento = jovem.DataNascimento;
            jov.NomeLocal = jovem.NomeLocal;
            jov.Rua = jovem.Rua;
            jov.Numero = jovem.Numero;
            jov.Bairro = jovem.Bairro;
            jov.Cidade = jovem.Cidade;
            jov.CEP = jovem.CEP;
            jov.UF = jovem.UF;
            jov.Pais = jovem.Pais;
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int? id)
        {
            Models.Jovem jovem = Dados.Db.jovens.FirstOrDefault(jv => jv.Id == id);
            return View(jovem);
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            Models.Jovem jovem = Dados.Db.jovens.FirstOrDefault(jv => jv.Id == id);
            return View(jovem);
        }

        [HttpPost]
        public IActionResult Delete(Models.Jovem jovem)
        {
            Models.Jovem jovemParaRemover = Dados.Db.jovens.FirstOrDefault(jv => jv.Id == jovem.Id);
            Dados.Db.jovens.Remove(jovemParaRemover);          
            return RedirectToAction("Index");
        }

    }
}

CadastroProjeto/Views/Jovem/Create.cshtml
@model CadastroProjeto.Models.Jovem
@{
    ViewData["Title"] = "Jovem";
}

<h1>CadastroProjeto</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="NomeLocal" class="control-label"></label>
                <input asp-for="NomeLocal" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Rua" class="control-label"></label>
                <input asp-for="Rua" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CEP" class="control-label"></label>
                <input asp-for="CEP" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="UF" class="control-label"></label>
                <input asp-for="UF" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
            </div>
            <div class="form-group mt-3">
                
                <input type="submit" value="Create" class="btn btn-primary" />
                
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CadastroProjeto/Views/Jovem/Delete.cshtml
<h1>TEM CERTEZA ? NÂO tem volta </h1>

<form asp-action="Delete">
    <button>Sim</button>
</form>

<form asp-action="Index">
    <button>Voltar</button>
</form>

CadastroProjeto/Views/Jovem/Details.cshtml
@model CadastroProjeto.Models.Jovem
@{
    ViewData["Title"] = "Jovem";
}
<h1>@ViewData["title"]</h1>
<div>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.Id):</span>
        @Html.DisplayFor(model => model.Id)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.Nome):</span>
        @Html.DisplayFor(model => model.Nome)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.Email):</span>
        @Html.DisplayFor(model => model.Email)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.Telefone):</span>
        @Html.DisplayFor(model => model.Telefone)
    </p>
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.DataNascimento):</span>
        @Html.DisplayFor(model => model.DataNascimento)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.NomeLocal):</span>
        @Html.DisplayFor(model => model.NomeLocal)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.Rua):</span>
        @Html.DisplayFor(model => model.Rua)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.Numero):</span>
        @Html.DisplayFor(model => model.Numero)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.Bairro):</span>
        @Html.DisplayFor(model => model.Bairro)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.Cidade):</span>
        @Html.DisplayFor(model => model.Cidade)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.CEP):</span>
        @Html.DisplayFor(model => model.CEP)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.UF):</span>
        @Html.DisplayFor(model => model.UF)
    </p>
    <p>
        <span class="fw-bold">@Html.DisplayNameFor(model => model.Pais):</span>
        @Html.DisplayFor(model => model.Pais)
    </p>
    @Html.ActionLink("Editar", "Edit", new {id=Model.Id}) |
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    <a asp-action="Index">Voltar</a>
</div>

CadastroProjeto/Views/Jovem/Edit.cshtml
@model CadastroProjeto.Models.Jovem
@{
    ViewData["Title"] = "Jovem";
}

<h1>Edit</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="NomeLocal" class="control-label"></label>
                <input asp-for="NomeLocal" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Rua" class="control-label"></label>
                <input asp-for="Rua" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CEP" class="control-label"></label>
                <input asp-for="CEP" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="UF" class="control-label"></label>
                <input asp-for="UF" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CadastroProjeto/Views/Jovem/Index.cshtml
@model IEnumerable<CadastroProjeto.Models.Jovem>
@{
    ViewData["title"] = "Jovem";
}
<h1 class="text">@ViewData["title"]</h1>
<p>
    <a asp-action="Create">Create</a>
</p>

@foreach (var item in Model)
{
    <div>
        <p>
            <span class="fw-bold">Id</span> : @Html.DisplayFor(model => item.Id)
        </p>
        <p>
            <span class="fw-bold">Nome</span> : @Html.DisplayFor(model => item.Nome)
        </p>
        <p>
            <span class="fw-bold">Email</span> : @Html.DisplayFor(model => item.Email)
            </p>
        <p>
            <span class="fw-bold">Telefone</span> : @Html.DisplayFor(model => item.Telefone)
        </p>
        <p>
            <span class="fw-bold">Data De Nascimento</span> : @Html.DisplayFor(model => item.DataNascimento)
        </p>
        <p>
            <span class="fw-bold">Nome Do Local</span> : @Html.DisplayFor(model => item.NomeLocal)
        </p>
        <p>
            <span class="fw-bold">Rua</span> : @Html.DisplayFor(model => item.Rua)
        </p>
        <p>
            <span class="fw-bold">Numero</span> : @Html.DisplayFor(model => item.Numero)
        </p>
        <p>
            <span class="fw-bold">Bairro</span> : @Html.DisplayFor(model => item.Bairro)
        </p>
        <p>
            <span class="fw-bold">Cidade</span> : @Html.DisplayFor(model => item.Cidade)
        </p>
        <p>
            <span class="fw-bold">CEP</span> : @Html.DisplayFor(model => item.CEP)
        </p>
        <p>
            <span class="fw-bold">UF</span> : @Html.DisplayFor(model => item.UF)
        </p>
        <p>
            <span class="fw-bold">Pais</span> : @Html.DisplayFor(model => item.Pais)
        </p>

        <div style="display:flex">
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.Id }) |
            @Html.ActionLink("Deletar", "Delete", new { id=item.Id })
        </div>
    </div>
}

CadastroProjeto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadastroProjeto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadastroProjeto.styles.css" asp-append-version="true" />

    @*<style>
    body {
    background-color: #ccffcc;
    }
    </style>*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CadastroProjeto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jovem" asp-action="Index">Cadastro Jovens</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empresa" asp-action="Index">Cadastro Empresas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CadastroProjeto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>