Nova pasta/ProjetoE21/Models/Curriculo.cs
namespace ProjetoE21.Models
{
    public class Curriculo
    {
        public string PerfilProfissional { get; set; }
        public string Cidade { get; set; }
        public DateTime InicioEscola { get; set; }
        public string Idioma1 { get; set; }
        public string NivelIdioma1 { get; set; }
        public string EscolaCidade { get; set; }
        public string? Idioma2 { get; set; }
        public string Ensino { get; set; }
        public string? NivelIdioma2 { get; set; }
        public int ValorIdioma1 { get; set; }
        public int ValorIdioma2 { get; set; }
        public int ValorIdioma3 { get; set; }
        public string Status { get; set; }
        public string? Idioma3 { get; set; }
        public string? NivelIdioma3 { get; set; }
        public string? Cursos { get; set; }
        public string? Outros1 { get; set; }
        public string? Outros2 { get; set; }
        public string? Outros3 { get; set; }
        public string? Outros4 { get; set; }
        public int Id { get; set; }
        public string Nome { get; set; }
        public Local Local { get; set; }
        public string Telefone { get; set; } 
        public string Email { get; set; } 
        public string RedeSocial { get; set; } 
        public string Objetivo { get; set; } 
        public string Escola { get; set; }
        public string Experiencia { get; set; }
        public int JovemId { get; set; } 
    }
}

Nova pasta/ProjetoE21/Models/Empresa.cs
using System.ComponentModel.DataAnnotations;

namespace ProjetoE21.Models
{
    public class Empresa
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Você deve informar o nome de sua empresa!")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Você deve informar o CNPJ de sua empresa!")]
        public string Cnpj { get; set; }
        public Local Local { get; set; }

        [Required(ErrorMessage = "Você deve informar o número para contato de sua empresa!")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Você deve informar o email de sua empresa!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Você deve informar a senha do perfil de sua empresa!")]
        public string Senha { get; set; }
    }
}

Nova pasta/ProjetoE21/Models/Jovem.cs
using System.ComponentModel.DataAnnotations;

namespace ProjetoE21.Models
{
    public class Jovem
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Você deve inserir seu nome!")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Você deve inserir seu email!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Você deve inserir seu número de telefone!")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Você deve inserir sua data de nascimento!")]
        public DateTime DataNascimento { get; set; }

        public Local Local { get; set; }

        [Required(ErrorMessage = "Você deve inserir o nome de seu responsável!")]
        public string Responsavel { get; set; }

        [Required(ErrorMessage = "Você deve inserir o telefone de seu responsável!")]
        public string FoneResponsavel { get; set; }

        [Required(ErrorMessage = "Você deve informar sua senha!")]
        public string Senha { get; set; }

        public Curriculo Curriculo = new();
    }
}

Nova pasta/ProjetoE21/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using PagedList;
using ProjetoE21.Dados;
using ProjetoE21.Dao;
using ProjetoE21.Models;

namespace ProjetoE21.Controllers
{
    public class LoginController : Controller
    {
        DaoCadastro DaoC = new();
        DaoEmpresa DaoEmp = new();

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Confirmar()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Empresa()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Empresa(Empresa empresa)
        {
            if (!ModelState.IsValid)
            {
                return View(empresa);
            }

            List<Empresa> empresas = DaoEmp.consultar();

            foreach(var i in empresas)
            {
                if (i.Email == empresa.Email)
                {
                    ModelState.AddModelError("userRepetido", "Este email já está cadastrado!");
                    return View(empresa);
                }
            }
            
            DaoEmp.adicionar(empresa);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CadastroJovem()
        {
            return View();
        }

        public IActionResult Deslogar()
        {
            Usuario.LogadoJ = null;
            Usuario.LogadoE = null;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult CadastroJovem(Jovem jovem)
        {
            if (!ModelState.IsValid)
            {
                return View(jovem);
            }

            List<Jovem> jovens = DaoC.consultar();

            foreach(var i in jovens)
            {
                if(i.Email == jovem.Email)
                {
                    ModelState.AddModelError("userRepetido", "Este email já está cadastrado!");
                    return View(jovem);
                }
            }

            DaoC.adicionar(jovem);

            return RedirectToAction("Index");

        }
    }
}

Nova pasta/ProjetoE21/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoE21.Models;
using ProjetoE21.Dados;
using ProjetoE21.Dao;

namespace ProjetoE21.Controllers
{
    public class PerfilController : Controller
    {
        DaoCadastro DaoC = new();
        DaoCurriculo DaoCur = new();
        DaoEmpresa DaoEmp = new();
        DaoFavoritos DaoF = new();
        DaoEmprego DaoE = new();

        public IActionResult Index()
        {
            if (Usuario.LogadoE == null)
            {
                return RedirectToAction("Jovem");
            }
            else
            {
                return RedirectToAction("Empresa");
            }
        }

        public IActionResult Desfavoritar(int id)
        {
            List<Emprego> empregos = DaoE.consultar();

            Emprego emprego = empregos.FirstOrDefault(em => em.Id == id);

            DaoF.deletar(emprego);

            return RedirectToAction("Jovem");
        }

        public IActionResult Jovem()
        {
            Listas.favoritos = DaoF.consultar();

            return View();
        }

        public IActionResult Empresa()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Editar()
        {
            Jovem jovem = Listas.cadastrosJ.FirstOrDefault(sc => sc.Id == Usuario.LogadoJ.Id);

            return View(jovem);
        }

        [HttpPost]
        public IActionResult Editar(Jovem jovem)
        {
            jovem.Id = Usuario.LogadoJ.Id;

            if (!ModelState.IsValid)
            {
                return View(jovem);
            }

            DaoC.editar(jovem);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditarEmpresa()
        {
            Empresa empresa = Listas.cadastrosE.FirstOrDefault(sc => sc.Id == Usuario.LogadoE.Id);

            return View(empresa);
        }

        [HttpPost]
        public IActionResult EditarEmpresa(Empresa empresa)
        {
            empresa.Id = Usuario.LogadoE.Id;

            if (!ModelState.IsValid)
            {
                return View(empresa);
            }

            DaoEmp.editar(empresa);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Curriculo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Curriculo(Curriculo curriculo)
        {
            curriculo.Nome = Usuario.LogadoJ.Nome;

            curriculo.Local = new();

            curriculo.Local = Usuario.LogadoJ.Local;
            curriculo.Telefone = Usuario.LogadoJ.Telefone;
            curriculo.Email = Usuario.LogadoJ.Email;

            DaoCur.adicionar(curriculo);

            List<Curriculo> curriculos = DaoCur.consultar();

            Usuario.LogadoJ.Curriculo = curriculos.FirstOrDefault(cr => cr.JovemId == Usuario.LogadoJ.Id);

            return RedirectToAction("Index");
        }
    }
}

Nova pasta/ProjetoE21/Views/Perfil/Editar.cshtml
@model ProjetoE21.Models.Jovem

<h1>Edite seu perfil</h1>

<form asp-action="Editar">
    <div>
        <label asp-for="Nome">Edite seu nome completo:</label>
        <input asp-for="Nome"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Nome)</span>
    </div>
    <div>
        <label asp-for="Email">Edite seu endereço de email:</label>
        <input asp-for="Email"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Email)</span>
    </div>
    <div>
        <label asp-for="Senha">Edite sua senha:</label>
        <input asp-for="Senha"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Senha)</span>
    </div>
    <div>
        <label asp-for="Telefone">Edite seu fone:</label>
        <input asp-for="Telefone"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Telefone)</span>
    </div>
    <div>
        <label asp-for="Local.Estado">Edite o estado de sua residência:</label>
        <input asp-for="Local.Estado"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Estado)</span>
    </div>
    <div>
        <label asp-for="Local.Cidade">Edite a cidade de sua residência:</label>
        <input asp-for="Local.Cidade"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Cidade)</span>
    </div>
    <div>
        <label asp-for="Local.Bairro">Edite o bairro de sua residência:</label>
        <input asp-for="Local.Bairro"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Bairro)</span>
    </div>
    <div>
        <label asp-for="Local.Rua">Edite a rua de sua residência:</label>
        <input asp-for="Local.Rua"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Rua)</span>
    </div>
    <div>
        <label asp-for="Local.Numero">Edite o número do local de sua residência:</label>
        <input asp-for="Local.Numero"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Numero)</span>
    </div>
    <div>
        <label asp-for="DataNascimento">Edite sua data de nascimento:</label>
        <input asp-for="DataNascimento" type="date"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.DataNascimento)</span>
    </div>
    <div>
        <label asp-for="Responsavel">Edite o nome de seu responsável:</label>
        <input asp-for="Responsavel"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Responsavel)</span>
    </div>
    <div>
        <label asp-for="FoneResponsavel">Edite o fone de seu responsável:</label>
        <input asp-for="FoneResponsavel"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.FoneResponsavel)</span>
    </div>

    <button asp-action="Editar" class="btn btn-warning">Editar</button>
</form>

Nova pasta/ProjetoE21/Views/Perfil/EditarEmpresa.cshtml
@model ProjetoE21.Models.Empresa

<h1>Edite seu perfil</h1>

<form asp-action="EditarEmpresa">
    <div>
        <label asp-for="Nome">Edite o nome da empresa:</label>
        <input asp-for="Nome"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Nome)</span>
    </div>
    <div>
        <label asp-for="Email">Edite o endereço de email da empresa:</label>
        <input asp-for="Email"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Email)</span>
    </div>
    <div>
        <label asp-for="Senha">Edite a senha:</label>
        <input asp-for="Senha"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Senha)</span>
    </div>
    <div>
        <label asp-for="Telefone">Edite o fone da empresa:</label>
        <input asp-for="Telefone"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Telefone)</span>
    </div>
    <div>
        <label asp-for="Local.Estado">Edite o estado de sua empresa:</label>
        <input asp-for="Local.Estado"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Estado)</span>
    </div>
    <div>
        <label asp-for="Local.Cidade">Edite a cidade de sua empresa:</label>
        <input asp-for="Local.Cidade"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Cidade)</span>
    </div>
    <div>
        <label asp-for="Local.Bairro">Edite o bairro de sua empresa:</label>
        <input asp-for="Local.Bairro"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Bairro)</span>
    </div>
    <div>
        <label asp-for="Local.Rua">Edite a rua de sua empresa:</label>
        <input asp-for="Local.Rua"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Rua)</span>
    </div>
    <div>
        <label asp-for="Local.Numero">Edite o número do local de sua empresa:</label>
        <input asp-for="Local.Numero"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Local.Numero)</span>
    </div>
    <div>
        <label asp-for="Cnpj">Edite o CNPJ de sua empresa:</label>
        <input asp-for="Cnpj"></input>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Cnpj)</span>
    </div>

    <button asp-action="EditarEmpresa" class="btn btn-warning">Editar</button>
</form>

Nova pasta/ProjetoE21/Views/Perfil/Empresa.cshtml
@using ProjetoE21.Dados;

@model ProjetoE21.Models.Curriculo;

<h1>Perfil</h1>

<h3>@Usuario.LogadoE.Nome</h3>
<p>Telefone: @Usuario.LogadoE.Telefone</p>
<p>Email: @Usuario.LogadoE.Email</p>

<div class="d-flex">
    <a asp-controller="Perfil" asp-action="EditarEmpresa" class="btn btn-warning me-2">Editar</a>
    <a asp-controller="Login" asp-action="Deslogar" class="btn btn-danger">Deslogar</a>
</div>

Nova pasta/ProjetoE21/Views/Perfil/Jovem.cshtml
@using ProjetoE21.Dados;

<div style="width:80vw;">
    <div style="justify-content:center; text-align:center;">
        <h1>Perfil</h1>
            <img src="~/css/Imagens/Perfil.png" width="25%"></img>
        <input type="file" id="foto"></input>
        <button onclick="enviarImagem()">Enviar</button>

        <h3>@Usuario.LogadoJ.Nome</h3>
        <p>Data de nascimento: @Usuario.LogadoJ.DataNascimento.Day/@Usuario.LogadoJ.DataNascimento.Month/@Usuario.LogadoJ.DataNascimento.Year</p>
        <p>Telefone: @Usuario.LogadoJ.Telefone</p>
        <p>Email: @Usuario.LogadoJ.Email</p>

        <h1>Responsável</h1>

        <p>Nome do responsável: @Usuario.LogadoJ.Responsavel</p>
        <p>Telefone do responsável: @Usuario.LogadoJ.FoneResponsavel</p>
    </div>

    <a asp-action="Curriculo">Adicionar curriculo</a>

    <div style="margin:auto; justify-content:center" class="d-flex">
        <a asp-controller="Perfil" asp-action="Editar" class="btn btn-warning me-2">Editar</a>
        <a asp-controller="Login" asp-action="Deslogar" class="btn btn-danger">Deslogar</a>
    </div>
</div>

<a href="https://wa.me/@Usuario.LogadoJ.Telefone">Enviar mensagem</a>

<hr />

<div style="justify-content:center; text-align:center;">
    <h1>Favoritos</h1>

    @if (Listas.favoritos.Count != 0)
    {
        foreach (var i in ProjetoE21.Dados.Listas.favoritos)
        {
            <div class="d-flex">
                <div class="card mb-5 hoverCard" style="width: 100%">
                    <div class="row g-0">
                        <div class="row flex-column">
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(model => i.Empresa.Nome)</h5>
                                <p class="card-text">
                                    @Html.DisplayFor(model => i.Descricao)
                                </p>
                                <p class="card-text">
                                <p name="rua">@Html.DisplayFor(model => i.Local.Rua)</p>  <p name="cidade">@Html.DisplayFor(model => i.Local.Cidade)</p>
                                <br>
                                <p name="distancia">Distancia</p>
                                <br>
                                    @Html.DisplayFor(model => i.HoraDeInicio.TimeOfDay) @Html.DisplayFor(model => i.HoraDeFim.TimeOfDay)
                                <br>
                                <span>Dias Trabalhados: </span>@Html.DisplayFor(model => i.DiasTrabalhados)
                                </p>
                                <div class="d-flex justify-content-between">
                                    <span>R$: @Html.DisplayFor(model => i.Salario)</span>
                                    <span> Data da postagem: 10/12</span>
                                </div>
                            </div>
                        </div>

                        <div class="d-flex justify-content-between">
                            <div class="card-body">
                                <a href="#" class="card-link" style="text-decoration:none; font-size:1em; color:green;">Candidatar</a>
                                <span class="card-link" style="text-decoration:none; font-size:1em; color:blue;">@Html.ActionLink("Desfavoritar", "Desfavoritar", new { Id = i.Id })</span>
                                <a href="#" class="card-link" style="text-decoration:none; font-size:1em; color:red;">Compartilhar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <p>Você ainda não tem vagas registradas como favoritas!</p>
    }
</div>
</div>

<script>
    document.onload = geocoding();

    async function enviarImagem() {
        const fileInput = document.getElementById('foto');
        const file = fileInput.files[0];

        const formData = new FormData();
        formData.append('image', file);

        try {
            const response = await fetch('https://api.imgur.com/3/image', {
                method: 'POST',
                headers: {
                    Authorization: 'Client-ID 98972d1924cf9ce'
                },
                body: formData
            });

            const data = await response.json();
            if (response.ok) {
                console.log(data);
                alert('Imagem enviada com sucesso! Link: ' + data.data.link);
            } else {
                alert('Erro ao enviar imagem: ' + data.data.error);
            }
        } catch (error) {
            alert('Ocorreu um erro ao enviar a imagem.');
            console.error('Erro:', error);
        }
    }

    async function geocoding() {
    @{
        var ruaJovem = Usuario.LogadoJ.Local.Rua;

        var cidadeJovem = Usuario.LogadoJ.Local.Cidade;
    }

                        var local = "@ruaJovem" + "+" + "@cidadeJovem";
        var url1 = `https://api.opencagedata.com/geocode/v1/json?q=${local}&key=de8ec31691d84fada09018809123c939&pretty=1`;

        var latitude1 = 0
        var longitude1 = 0;

        await fetch(url1)
            .then(data => data.json())
            .then(item => {
                latitude1 = parseFloat(item.results[0].geometry.lat)

                longitude1 = parseFloat(item.results[0].geometry.lng)
            })

        var ruas = document.getElementsByName("rua")
        var cidades = document.getElementsByName("cidade")
        var distancias = document.getElementsByName("distancia")

        for (var i = 0; i < ruas.length; i++) {
            var endereco = `${ruas[i].innerHTML} + ${cidades[i].innerHTML}`
            var url2 = `https://api.opencagedata.com/geocode/v1/json?q=${endereco}&key=de8ec31691d84fada09018809123c939&pretty=1`

            var latitude2;
            var longitude2;

            await fetch(url2)
                .then(data => data.json())
                .then(item => {
                    console.log(item)

                    latitude2 = parseFloat(item.results[0].geometry.lat)

                    longitude2 = parseFloat(item.results[0].geometry.lng)
                })

            var distancia = formulaDeHaversine(latitude1, longitude1, latitude2, longitude2);

            distancias[i].innerHTML = `${distancia}km`;
        }
    }

    function toRadians(degrees) {
        return degrees * Math.PI / 180;
    }

    function formulaDeHaversine(lat1, lon1, lat2, lon2) {
        var R = 6371;
        var dLat = toRadians(lat2 - lat1);
        var dLon = toRadians(lon2 - lon1);

        var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
            Math.cos(toRadians(lat1)) * Math.cos(toRadians(lat2)) *
            Math.sin(dLon / 2) * Math.sin(dLon / 2);

        var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

        var distance = R * c;

        return distance.toFixed(2);
    }
</script>